/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Mzj0g3nF9Ic
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { imagesAreas } from "@/constants"

export function Areas() {
  return (
    <section className="flex flex-col items-center justify-center gap-8 py-12 md:py-24">
      <div className="container px-4 md:px-6 grid grid-cols-1 gap-8 sm:grid-cols-3">
        {imagesAreas.map((image, index) => (
          <div className="flex flex-col items-center justify-center gap-4 rounded-lg border bg-background p-6 text-center shadow-sm  h-72 " style={{ backgroundImage: `url(${image})` }} key={index}>
          <h3 className="text-2xl font-bold">Box 1</h3>
          <p className="text-muted-foreground">
            This is the content for the first box. It can include any relevant information or a call-to-action.
          </p>
          <Button className="mt-4">Acessar</Button>
        </div>
        ))}
      </div>
    </section>
  )
}
