/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nEs0DYVe64E
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function BlogBlock() {
  return (
    <section className="py-12 md:py-16 lg:py-20">
      <div className="container mx-auto px-4 md:px-6 lg:px-8">
        <div className="mb-8 md:mb-10 lg:mb-12">
          <h2 className="text-2xl font-bold tracking-tight md:text-3xl lg:text-4xl">Latest from the Blog</h2>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <div className="rounded-lg overflow-hidden shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1692827728176-955e9588dede?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Blog Post Image"
              width={400}
              height={225}
              className="w-full h-48 object-cover"
            />
            <div className="p-6 bg-background">
              <h3 className="text-lg font-semibold mb-2">Mastering React Hooks: A Comprehensive Guide</h3>
              <p className="text-muted-foreground mb-4">
                Discover the power of React Hooks and learn how to leverage them to build more efficient and
                maintainable applications.
              </p>
              <Link
                href="#"
                className="inline-flex items-center font-medium text-primary hover:text-primary-foreground"
                prefetch={false}
              >
                Read more
                <ArrowRightIcon className="ml-1 w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="rounded-lg overflow-hidden shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1692827728176-955e9588dede?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Blog Post Image"
              width={400}
              height={225}
              className="w-full h-48 object-cover"
            />
            <div className="p-6 bg-background">
              <h3 className="text-lg font-semibold mb-2">Optimizing Website Performance: Best Practices</h3>
              <p className="text-muted-foreground mb-4">
                Learn proven techniques to improve your website's speed and responsiveness, providing a better user
                experience.
              </p>
              <Link
                href="#"
                className="inline-flex items-center font-medium text-primary hover:text-primary-foreground"
                prefetch={false}
              >
                Read more
                <ArrowRightIcon className="ml-1 w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="rounded-lg overflow-hidden shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1692827728176-955e9588dede?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Blog Post Image"
              width={400}
              height={225}
              className="w-full h-48 object-cover"
            />
            <div className="p-6 bg-background">
              <h3 className="text-lg font-semibold mb-2">Designing Accessible Interfaces: A Primer</h3>
              <p className="text-muted-foreground mb-4">
                Explore the principles of accessible web design and learn how to create inclusive experiences for all
                users.
              </p>
              <Link
                href="#"
                className="inline-flex items-center font-medium text-primary hover:text-primary-foreground"
                prefetch={false}
              >
                Read more
                <ArrowRightIcon className="ml-1 w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="rounded-lg overflow-hidden shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1692827728176-955e9588dede?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Blog Post Image"
              width={400}
              height={225}
              className="w-full h-48 object-cover"
            />
            <div className="p-6 bg-background">
              <h3 className="text-lg font-semibold mb-2">Scaling Your React Application: Strategies and Techniques</h3>
              <p className="text-muted-foreground mb-4">
                Discover effective strategies and techniques to scale your React applications, ensuring they can handle
                growing user demands.
              </p>
              <Link
                href="#"
                className="inline-flex items-center font-medium text-primary hover:text-primary-foreground"
                prefetch={false}
              >
                Read more
                <ArrowRightIcon className="ml-1 w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="rounded-lg overflow-hidden shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1692827728176-955e9588dede?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Blog Post Image"
              width={400}
              height={225}
              className="w-full h-48 object-cover"
            />
            <div className="p-6 bg-background">
              <h3 className="text-lg font-semibold mb-2">Building Robust State Management in React</h3>
              <p className="text-muted-foreground mb-4">
                Explore the best practices and patterns for managing state in your React applications, ensuring
                consistency and scalability.
              </p>
              <Link
                href="#"
                className="inline-flex items-center font-medium text-primary hover:text-primary-foreground"
                prefetch={false}
              >
                Read more
                <ArrowRightIcon className="ml-1 w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="rounded-lg overflow-hidden shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1692827728176-955e9588dede?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Blog Post Image"
              width={400}
              height={225}
              className="w-full h-48 object-cover"
            />
            <div className="p-6 bg-background">
              <h3 className="text-lg font-semibold mb-2">Mastering TypeScript in React: A Comprehensive Guide</h3>
              <p className="text-muted-foreground mb-4">
                Learn how to leverage the power of TypeScript to build more robust and maintainable React applications.
              </p>
              <Link
                href="#"
                className="inline-flex items-center font-medium text-primary hover:text-primary-foreground"
                prefetch={false}
              >
                Read more
                <ArrowRightIcon className="ml-1 w-4 h-4" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
