/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/r9PI0CGzQEn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Hero() {
  return (
    <section
      className="relative w-full h-[60vh] flex items-center justify-center bg-cover bg-center"
      style={{ backgroundImage: 'url("/hero-bg.jpg")' }}
    >
      <div className="absolute inset-0 bg-black/50 z-0" />
      <div className="relative z-10 text-center space-y-6 max-w-3xl px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
          Unlock the Power of Web Development
        </h1>
        <p className="text-xl text-gray-300">
          Discover our comprehensive suite of tools and resources to build exceptional web experiences.
        </p>
        <div>
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md bg-primary px-8 py-3 text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            Get Started
          </Link>
        </div>
      </div>
    </section>
  )
}
