/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZNu2CD71Q0K
**/

import Link from "next/link"
import { imagesExemples } from "@/constants"
export function ImageGalery() {
  return (
    <section className="w-full py-12 md:py-24">
      <div className="container px-4 md:px-6 mx-auto">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Explore Our Mosaic Gallery</h2>
          <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Discover a captivating collection of diverse images in our mosaic gallery.
          </p>
        </div>
        <div className=" columns-1 sm:columns-2 lg:columns-3 py-10 md:py-20 gap-4">
          {imagesExemples.map((image, index) => {
            return (
              <div key={index} className="mb-4 break-inside-avoid">
                <img
                  src={image}
                  alt="Gallery Image"
                  className="w-full object-cover rounded-lg"
                />
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}