/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lJwnQlHSEBA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/Sheet";
import { Button } from "@/components/ui/Button";
import Link from "next/link";
import { menu }  from "@/constants";

export function Navbar() {
  const buildMenu = () => {
    return menu.map((item, index) => {
      return (
        <Link
          key={index}
          href={item.href}
          className="flex w-full items-center py-2 text-lg whitespace-nowrap"
          prefetch={false}
        >
          {item.name}
        </Link>
      );
    });
  };

  return (
    <header className="container mx-auto flex h-20  items-center px-4 md:px-6 relative">
      <Sheet>
        <SheetTrigger className="absolute" asChild>
          <Button variant="outline" size="icon" className="lg:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <MountainIcon className="h-6 w-6 mx-auto lg:hidden" />
        <SheetContent side="left">
          <Link href="/" className="mr-6 hidden lg:flex" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <div className="grid gap-2 py-6">
            {buildMenu()}
            <Button variant="outline" className="text-lg">Contato</Button>
          </div>
        </SheetContent>
      </Sheet>
      <Link href="/" className="mr-6 hidden lg:flex" prefetch={false}>
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <nav className="ml-auto hidden lg:flex gap-6">
        {buildMenu()}
        <Button variant="outline" className="text-lg">Contato</Button>
      </nav>
    </header>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}


