/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hGqapeEJi5x
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Topbar() {
  return (
    <div className="bg-primary text-primary-foreground py-2 px-4 text-center">
      <p className="text-sm font-medium">Limited time sale - 50% off everything!</p>
    </div>
  )
}
