/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GeyURwRwJkY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Button } from "./ui/button";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TwoColumnsText() {
  return (
    <div className="container mx-auto py-12 px-4 md:px-6 lg:py-16">
      <div className="grid grid-cols-1 gap-8">
        <div>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Introducing our new product</h2>
        </div>
        <div className="grid grid-cols-2 gap-8">
          <div>
            {/* <h3 className="text-xl font-semibold mb-4">Features</h3> */}
            <p className="text-muted-foreground">
              Our new product comes with a range of features to make your life easier. From automated workflows to
              powerful analytics, we've got you covered.
            </p>
          </div>
          <div>
            {/* <h3 className="text-xl font-semibold mb-4">Benefits</h3> */}
            <p className="text-muted-foreground">
              Using our new product will provide you with a number of benefits, including increased productivity, better
              decision-making, and more. Experience the difference today.
            </p>
          </div>
        </div>
        <Button variant="link" className=" justify-end">Saiba Mais ... </Button>
      </div>
    </div>
  )
}
