/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GeyURwRwJkY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Button } from "./ui/button";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TwoColumnsText() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12 md:py-24">
      <div className="grid grid-cols-1 gap-8">
        <div>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Introducing our new product</h2>
        </div>
        <div className="grid lg:grid-cols-2 gap-8">
          <div>
            {/* <h3 className="text-xl font-semibold mb-4">Features</h3> */}
            <p className="text-muted-foreground">
              Our new product comes with a range of features to make your life easier. From automated workflows to
              powerful analytics, we've got you covered.
            </p>
          </div>
          <div>
            {/* <h3 className="text-xl font-semibold mb-4">Benefits</h3> */}
            <p className="text-muted-foreground">
              Using our new product will provide you with a number of benefits, including increased productivity, better
              decision-making, and more. Experience the difference today.
            </p>
          </div>
        </div>
        <Button variant="link" className=" justify-end">Saiba Mais <ArrowRightIcon className="ml-1 w-4 h-4" /> </Button>
      </div>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}