/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GeyURwRwJkY
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */


import ArrowRightIcon from "./ui/ArrowRightIcon";
import { Button } from "./ui/Button";

interface TwoColumnsTextProps {
  title?: string;
  column1?: string;
  column2?: string;
  hasButton: boolean;
}

export function TwoColumnsText({
  title = "Introducing our new product",
  column1 = "Our new product comes with a range of features to make your life easier. From automated workflows to powerful analytics, we've got you covered.",
  column2 = "Using our new product will provide you with a number of benefits, including increased productivity, better decision-making, and more. Experience the difference today.",
  hasButton = false,
}: TwoColumnsTextProps) {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12 md:py-24">
      <div className="grid grid-cols-1 gap-8">
        <div>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2>
        </div>
        <div className="grid lg:grid-cols-2 gap-8">
          <div>
            <p className="text-muted-foreground">{column1}</p>
          </div>
          <div>
            <p className="text-muted-foreground">{column2}</p>
          </div>
        </div>
        {hasButton && (
          <Button variant="link" className="justify-end">
            Saiba Mais <ArrowRightIcon className="ml-1 w-4 h-4" />
          </Button>
        )}
      </div>
    </div>
  );
}
